name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: SSH into the server and delete old files
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: hawkings.dev
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/matchapp/html/*

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: hawkings.dev
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/var/www/matchapp/html/"
